using System.ComponentModel;
using System.Globalization;
using ModelContextProtocol.Server;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddMcpServer().WithHttpTransport(options => options.Stateless = true).WithTools<SmartRoomTools>();
var app = builder.Build();
app.MapGet("/", () => "healthy");
app.MapGet("/favicon.ico", () => Results.NoContent());
app.MapMcp("/mcp");
app.Run();

[McpServerToolType]
public class SmartRoomTools
{
    [McpServerTool(Name = "get_version")]
    [Description("Returns SmartRoom MCP version")]
    public string GetVersion(
        [Description("Audit correlation identifier generated by the main MCP gateway")] string correlationId = "")
    {
        return ExecuteWithAudit(correlationId, nameof(GetVersion), () => "smartroom_v1");
    }

    [McpServerTool(Name = "get_smartrooms_data")]
    [Description("Returns simulated SmartRoom report data. Use reportName 'smartrooms_per_day' for smartroom counts by day, or 'users_per_smartroom' for user counts grouped by smartroom.")]
    public SmartRoomReportData GetSmartroomsData(
        [Description("Start date/time for the report range")] DateTime from,
        [Description("End date/time for the report range")] DateTime to,
        [Description("Report name: smartrooms_per_day or users_per_smartroom")] string reportName,
        [Description("Audit correlation identifier generated by the main MCP gateway")] string correlationId = "")
    {
        return ExecuteWithAudit(correlationId, nameof(GetSmartroomsData), () =>
        {
            if (to < from)
            {
                throw new ArgumentException("'to' must be greater than or equal to 'from'.");
            }

            var normalizedReportName = reportName.Trim().ToLowerInvariant();
            return normalizedReportName switch
            {
                "users_per_smartroom" => CreateUsersPerSmartroomReport(from, to, reportName, correlationId),
                "smartrooms_per_day" => CreateSmartroomsPerDayReport(from, to, reportName, correlationId),
                _ when normalizedReportName.Contains("user", StringComparison.OrdinalIgnoreCase) =>
                    CreateUsersPerSmartroomReport(from, to, reportName, correlationId),
                _ => CreateSmartroomsPerDayReport(from, to, reportName, correlationId)
            };
        });
    }

    private static SmartRoomReportData CreateSmartroomsPerDayReport(DateTime from, DateTime to, string reportName, string correlationId)
    {
        var seed = Math.Abs(HashCode.Combine(reportName, from.Date, to.Date));
        var days = Math.Min((to.Date - from.Date).Days + 1, 31);
        var rows = Enumerable.Range(0, days)
            .Select(index =>
            {
                var date = from.Date.AddDays(index);
                var value = 6 + ((seed + index * 11) % 18);
                return new SmartroomsPerDayRow(
                    date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
                    value);
            })
            .ToList<object>();

        return new SmartRoomReportData(correlationId, reportName, rows);
    }

    private static SmartRoomReportData CreateUsersPerSmartroomReport(DateTime from, DateTime to, string reportName, string correlationId)
    {
        string[] smartroomNames =
        [
            "Bank of America Executive SmartRoom",
            "Boeing Engineering SmartRoom",
            "Contoso Operations SmartRoom",
            "Fabrikam Finance SmartRoom",
            "Northwind Trading SmartRoom"
        ];

        var seed = Math.Abs(HashCode.Combine(reportName, from.Date, to.Date));
        var rows = smartroomNames
            .Select((smartroomName, index) =>
            {
                var date = from.Date.AddDays(index % Math.Max(1, Math.Min((to.Date - from.Date).Days + 1, 31)));
                var numberOfUsers = 25 + ((seed + index * 37) % 275);
                return (object)new UsersPerSmartroomRow(
                    smartroomName,
                    numberOfUsers,
                    date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
            })
            .ToList();

        return new SmartRoomReportData(correlationId, reportName, rows);
    }

    private static T ExecuteWithAudit<T>(string correlationId, string methodName, Func<T> action)
    {
        Console.WriteLine($"[{DateTimeOffset.UtcNow:O}] correlationId={correlationId} method={methodName} status=start");
        try
        {
            var result = action();
            Console.WriteLine($"[{DateTimeOffset.UtcNow:O}] correlationId={correlationId} method={methodName} status=end");
            return result;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[{DateTimeOffset.UtcNow:O}] correlationId={correlationId} method={methodName} status=error error=\"{ex.Message}\"");
            throw;
        }
    }
}

public sealed record SmartRoomReportData(string CorrelationId, string ReportName, List<object> Data);

public sealed record SmartroomsPerDayRow(string Date, int Value);

public sealed record UsersPerSmartroomRow(string SmartroomName, int NumberOfUsers, string Date);
